### PR TITLE
Add/update svg for most images in current design.

### PR DESCRIPTION
**Pull request by dougfelt**
SVG conversion issues prevented 54 images from being updated:
emoji_u2648.svg
emoji_u1f321.svg
emoji_u1f34c.svg
emoji_u1f35b.svg
emoji_u1f377.svg
emoji_u1f3f5.svg
emoji_u1f468_1f3fb_200d_1f680.svg
emoji_u1f468_1f3fc_200d_1f680.svg
emoji_u1f468_1f3fd_200d_1f680.svg
emoji_u1f468_1f3fe_200d_1f680.svg
emoji_u1f468_1f3ff_200d_1f680.svg
emoji_u1f468_200d_1f680.svg
emoji_u1f469_1f3fb_200d_1f680.svg
emoji_u1f469_1f3fc_200d_1f680.svg
emoji_u1f469_1f3fd_200d_1f680.svg
emoji_u1f469_1f3fe_200d_1f680.svg
emoji_u1f469_1f3ff_200d_1f680.svg
emoji_u1f469_200d_1f680.svg
emoji_u1f47c_1f3fb.svg
emoji_u1f47c_1f3fc.svg
emoji_u1f47c_1f3fd.svg
emoji_u1f47c_1f3fe.svg
emoji_u1f47c_1f3ff.svg
emoji_u1f47c.svg
emoji_u1f4f8.svg
emoji_u1f4ff.svg
emoji_u1f5c2.svg
emoji_u1f5de.svg
emoji_u1f644.svg
emoji_u1f6eb.svg
emoji_u1f6ec.svg
emoji_u1f6f0.svg
emoji_u1f6f4.svg
emoji_u1f6f5.svg
emoji_u1f6f6.svg
emoji_u1f911.svg
emoji_u1f912.svg
emoji_u1f914.svg
emoji_u1f915.svg
emoji_u1f917.svg
emoji_u1f918.svg
emoji_u1f922.svg
emoji_u1f923.svg
emoji_u1f924.svg
emoji_u1f942.svg
emoji_u1f943.svg
emoji_u1f94a.svg
emoji_u1f952.svg
emoji_u1f953.svg
emoji_u1f981.svg
emoji_u1f989.svg
emoji_u1f98a.svg
emoji_u1f98f.svg
emoji_u1f991.svg

### CODE REVIEW

**Comment by asturur** [comment]
can i ask if the conversion process you talk about is made with files in this repository?

**Comment by dougfelt** [comment]
No, we start from Adobe Illustrator files.

**Comment by asturur** [comment]
thanks very much for the update.

**Comment by dougfelt** [comment]
Sorry about the missing files.  Need to get a designer to fix them, or see if I can do it.

**Comment by asturur** [comment]
I have a question. does this SVG resemble the actual PNGs? to me they look the old style.

**Comment by asturur** [comment]
sorry i just forgot to push the merge button in my fork. thanks very much.

**Pull request merged**
