### PR TITLE
Pistol change

### PR DESCRIPTION
**Pull request by dougfelt**

### CODE REVIEW

**Comment by asturur** [comment]
Hey, i'm very curious about the reason behind this change, a change i like.
Do you have some detail?

**Comment by fitojb** [comment]
@asturur The change was obviously done to harmonize with other vendors’ emoji fonts, so as to convey the same meaning across devices.

**Comment by asturur** [comment]
For a moment i thought it was because this pistol looks less bad than the old pistol.

Opinion wise: Well i think quality and nice emoji should be over harmony since if people wants different devices let them have slightly different emoji.
I would always take a nicer design over a conformant one.

**Comment by jbicha** [comment]
@asturur https://blog.emojipedia.org/google-updates-gun-emoji/

See also the harsh criticism Apple initially got for the change because there's a big difference in meaning between realistic handgun and toy water gun. https://blog.emojipedia.org/apple-and-the-gun-emoji/

**Pull request merged**
