### PR TITLE
Use big glyph metrics to support vertical text rendering

### PR DESCRIPTION
**Pull request by yuki-takeichi**
`NotoColorEmoji.ttf` embeds smallGlyphMetrics in CBDT.
Freetype sets `vertBearingX`, `vertBearingY` and `vertAdvance` to 0 when smallGlyphMetrics is used.
http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/src/sfnt/ttsbit.c?h=VER-2-8-1#n672

So when it is used to layout vertical text with emoji, it can cause some problems.

For instance, when I try to layout `麦酒(beer) 🍺🍻🍺🍻😂` vertically by using Pango with Cairo as a graphic backend, it renders emoji at an incorrect place:

output

(The emoji graphics are rendered at the same place because `vertAdvance` is set to 0, and exceeds the baseline because `vertBearingX` is set to 0.)

So I rebuild `NotoColorEmoji.ttf` that embeds bigGlyphMetrics, and it renders emoji correctly:

output

Here is a source code.
https://gist.github.com/yuki-takeichi/f9c1b7bf9154597518fbd9289b527004
(Cairo 1.15.8, Pango 1.40.14, FreeType 2.8.1)

### CODE REVIEW

**Comment by yuki-takeichi** [comment]
@googlebot I signed it!

**Comment by dougfelt** [comment]
Thanks very much!

Could you please you remove the binary font from this pull request?  We generally only upload binaries we built ourselves, and we would also want to update the fontRevision and name table version string.

**Comment by yuki-takeichi** [comment]
@dougfelt I removed the binary.

**Comment by dougfelt** [comment]
Thank you

**Comment by yuki-takeichi** [comment]
@dougfelt Would you mind adding me to `CONTRIBUTOR` list?

**Comment by dougfelt** [comment]
Sure.  Please edit it to add your name and email address at the end, and I'll accept the pull request.

**Pull request merged**
